[profile.default]
src = "src"
out = "out"
script = 'script'
libs = ["lib"]
solc = '0.8.13'
evmVersion = "london"
# Enabling optimizations to improve gas usage.
optimizer = true
optimizer_runs = 200
via_ir = false
evm_version = "cancun"

fs_permissions = [
    { access = "read", path = "./out/" },
    { access = "read", path = "./script/input/" },
    { access = "read-write", path = "./script/output/" },
]

[rpc_endpoints]
mainnet = "${ETH_RPC_URL}"

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}", chain = 1 }
unknown_chain = { key = "${TENDERLY_ACCESS_KEY}", chain = 314311, url = "${ETH_RPC_URL}/verify/etherscan" }
